import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className="m-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl leading-6">2022年度こうがく祭HP 鋭意制作中</h1>
      </main>
      <footer className="mt-4">©2022年度こうがく祭実行委員会</footer>
    </div>
  );
};

export default Home;
