import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Heading } from 'components/Typography';
import kougakusai_banner from '@public/kougakusai_banner.png';

const Home: NextPage = () => {
  return (
    <div className="m-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>2022年度こうがく祭HP 鋭意制作中</Heading>
      </main>
      <footer className="mt-4">©2022年度こうがく祭実行委員会</footer>
      <Image
        src={kougakusai_banner}
        alt="こうがく祭バナー"
        width={400}
        height={150}
      />
    </div>
  );
};

export default Home;
