import type { NextPage } from 'next';
import Head from 'next/head';
import { Heading } from 'components/Typography/Heading';

const Home: NextPage = () => {
  return (
    <div className="m-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>2022年度こうがく祭HP 鋭意制作中</Heading>
      </main>
      <footer className="mt-4">©2022年度こうがく祭実行委員会</footer>
    </div>
  );
};

export default Home;
